### ISSUE TITLE
SVG Polyline vs. SVG Path in output

### ISSUE THREAD

**Issue by theomega** [abey79/vpype#174]
Currently vpype writes SVG Polylines. Is there a reason for using them vs. using SVG Paths? 

Reason I'm asking: My toolchain currently involves opening the SVG in Inkscape and then using an Inkscape plugin to generate the GCode to send to my pen plotter. This Inkscape plugin only supports SVG Paths, so I have to convert the Polylines from vpype to Paths. This is two clicks, but I was wondering what the rational was.

I'm thinking to implement a command line flag to the `write` command to switch the output to SVG Paths from SVG Polylines. Would such a thing make sense in the scope of the project?

**Comment by abey79** [comment]
I actually recently changed from path to polylines. The reasons were polylines are more compact than paths since it's just a bunch of coordinate, without the "M" and "L" commands and they happen to be much faster to load in vpype (should you `read` a file that was previously written by vpype).

Now, in order to optimise your workflow, I strongly suggest to take a look at https://github.com/tatarize/vpype-gcode/. It's in a rather preliminary state and might need some coding to adjust to your needs, but I know @tatarize is always willing to help on this.

**Comment by theomega** [comment]
Ok, lets leave it like this, the argument that polylines are shorter is a strong one.
