### ISSUE TITLE
Linesort breaking straight lines 

### ISSUE THREAD

**Issue by ithinkido** [abey79/vpype#32]
When using linesort on a drawing with straight lines , I am getting a lot of mini lines instead of a single connected line segment.
I am running this command line

vpype read blockhouse.svg linemerge --tolerance 0.1mm linesort write --layer-label Pen%d --page-format 192x270mm blockhouse_opt.svg

This is the original
![Screenshot from 2020-04-30 11-36-51](https://user-images.githubusercontent.com/52834821/80696669-00d8d200-8ad8-11ea-9909-1099ec91beed.png)

This is the output
![Screenshot from 2020-04-30 11-33-33](https://user-images.githubusercontent.com/52834821/80695658-822f6500-8ad6-11ea-9016-33a4299429f4.png)

this is the plot that I am using

[blockhouse.zip](https://github.com/abey79/vpype/files/4557462/blockhouse.zip)

**Comment by abey79** [comment]
The root cause is the fact that your SVG paths are made of (straight) curves instead of lines:

<img width="407" alt="image" src="https://user-images.githubusercontent.com/49431240/80708217-9598fb00-8aeb-11ea-948e-5dee59a77f3f.png">

(Notice the "c" in the `d` attribute.)

vpype converts everything to poly lines on input, and will quantise curves based on the `--quantization` parameter. Apparently, the implicit `linesimplify` of the `read` command is not able to completely cope with it It does, to some extend, eg. compare:

```
vpype read blockhouse.svg show -d
vpype -s read blockhouse.svg show -d
```

(You'll need to update vpype before, I just added `-d`.)

I suggest you look at whatever generated the file to see if you can have it generate lines instead of curves. It may very well be that the situation will improve when #31 is fixed too.

**Comment by ithinkido** [comment]
It is not causing extra pen up movements, but the extra segments mean that the plotter handles each one after the other and is in constant acceleration-deceleration for each segment. When there are many small segments, the motion is kind of jittery

**Comment by ithinkido** [comment]
That - d is very useful. I can not use the -s , I am getting an "not valid integer' error, but still i get the idea, the lines are not lines, but curves and that is not great for optimization.

**Comment by abey79** [comment]
Sorry the -s was meant to be after the read, not before. I fixed it up there.

**Comment by abey79** [comment]
Hey @ithinkido, I revisited this following the resolution of #34, and although the implicit simplify in `read` still has issues (#31), an explicit `linesimplify` now cleans your example file nicely:

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/49431240/81930253-a320ab80-95e8-11ea-9d81-a9ff428986fa.png">

**Comment by ithinkido** [comment]
Super clean !! Thanks

**Comment by haschdl** [comment]
sorry to open and old topic, but since my issue is identical to the one initially reported here by @ithinkido , I decided writing a comment instead of opening a new issue.  I read @abey79  [comment](https://github.com/abey79/vpype/issues/32#issuecomment-621795421 ) and while I understand that "vpype converts everything to poly lines on input" I still would like to know if there is a way to prevent that, when my primary goal is to use only `linemerge`.

In other words, I would like to use the power of `linemerge` and leave the rest intact. The reason for that is what the initial post mentioned, it affects the plot results.

Here is an example, on the right the result after `linemerge`
![image](https://user-images.githubusercontent.com/9550197/160704830-e2a03e0d-ea2c-47d3-9657-4570cf29dc97.png)

The SVG is created using Processing and its `arc()` command (using `bezier()` has the same effect).  
I am using vpype 1.9.0, the entire command is:
```
vpype read --single-layer 20220329174853.svg linemerge write out.svg
```

**Comment by abey79** [comment]
Hello @haschdl. No, there is currently no way around the linearisation at all. I'm kind of thinking of getting there, but it'll take an entire rewrite of pretty much everything, so it could be years until that happens (if at all).

As a side note, a "line-merge-only" Python script could conceivably be hacked without much hassle using svgelements to extract path elements and using the same merging algorithm as vpype, since it only considers end points. But that would be just a script. There is currently no way to fit this into vpype.

**Comment by ithinkido** [comment]
@haschdl  take a look at this. It should do what you are looking for. https://github.com/fablabnbg/inkscape-chain-paths

**Comment by haschdl** [comment]
@abey79  thank you, I understand it now.  I will check the alternatives. 
@ithinkido thanks for the tip! `inkscape-chain-paths` looks like the right solution, but unfortunately it didn't work in Inskcape 1.1 with my drawing. It could be a good starting point to get hands-on, as it is just one script. Are you using the extension?

**Comment by ithinkido** [comment]
Yes, I used it an hour ago in 1.1. Still seems to work for me.
