### ISSUE TITLE
`read` should discard invisible geometries

### ISSUE THREAD

**Issue by abey79** [abey79/vpype#85]

**Comment by abey79** [comment]
@tatarize do you happen to have a good heuristic to determine if a given SVG element should be visible or not? I see there is at least the `visibility` and `display` attributes. Anything else? Is that something you already have somewhere?

**Comment by tatarize** [comment]
The only thing regularly seen is visibility='hidden'. Which is element.values['visibility'] == 'hidden', likely in a try block. Oddly enough I don't correctly deal with the display attribute in svgelements, in theory if it says display="none", it shouldn't block the return the actual parsing. Since it actually means that it prevents rendering. In theory there's also rectangles that if they have 0 width they don't actually become paths, but really blank paths.

**Comment by abey79** [comment]
OK so I need to implement `visibility` and wait for meerk40t/svgelements#70

**Comment by tatarize** [comment]
You could also check for display, but I've generally not seen it come up. I was just double-checking here and realized that it's actually the case that that means do not render on my part. But, yeah, you would check visibility on your end since that's a real rendered item but is hidden. Whereas display is not rendered at all, even invisibly.

**Comment by tatarize** [comment]
Apparently for not going to happen completeness `if element.values['visibility'] in ('hidden', 'collapse'):` According to the spec the CSS for tables to collapse something if applied to an SVG should have the same effect as hidden.

**Comment by tatarize** [comment]
The meerk40t/svgelements#70 should be finished. Added solid test coverage for it too. Also properly corrected the width/height thing the zerodivideerror was the failure of the viewbox. WIth a viewbox zero we get infinite length with the width/height zero we everything scales into a singularity in the origin, but notably wouldn't throw an error since multipling everything by zero is fine. Added test coverage for everything and published 1.3.4 on pypi as well as the project page.

**Comment by abey79** [comment]
Awesome, thanks!
